Stage 1 | Completed
ilya-xbsoftware/jet-start pull request #1
Opened 2021-04-22 21:00 UTC by ilya-xbsoftware

2021-04-23 08:56 UTC, igr-ik reviewed
Не нужно тратить время на кастомную стилизацию компонентов. Оставляй все в стандартных стилях вебикса. Исключения HTML структура которую ты создаешь сам.

2021-04-23 08:56 UTC, igr-ik commented on sources/constants/urls.js
> +const LOCAL_PHOTO_URL = "./sources/images/man.png";
Логичней было бы назвать PLACEHOLDER_AVATAR_URL

2021-04-23 08:56 UTC, igr-ik commented on sources/views/activities.js
> +								this.ui(new PopupView(this.app, ""))._showWindow();
1) Каждый раз, когда ты нажимаешь эту кнопку, создается новый экземпляр попапа. Экземпляр попапа нужно сохранить в переменную и у нее вызывать _showWindow()
2) Методы название через нижнее подчеркивание, означают что приватные и используются только внутри класса. Сейчас ты приватный метод используешь вне класса

2021-04-23 08:56 UTC, igr-ik commented on sources/views/activities.js
> +		});
Это можно было написать в самом view  "datatable", пример:
{
    view: "datatable",
    on : {
        onAfterSelect: (id) => {
            this.show(`../activities?id=${id}`);
        }
    }
}

2021-04-23 08:56 UTC, igr-ik commented on sources/views/activities.js
> +	_deleteRow(id) {
Ты удаляешь не строчку таблицы, а сущность "activity", названия должно быть соответствующим  _deleteActivity

2021-04-23 08:56 UTC, igr-ik commented on sources/views/activities.js
> +	_editRow(id) {
Здесь тоже  _editActivity

2021-04-23 08:56 UTC, igr-ik commented on sources/views/activities.js
> +		this.ui(new PopupView(this.app, "", id))._showWindow(id);
1) Каждый раз, когда ты нажимаешь эту кнопку, создается новый экземпляр попапа. Экземпляр попапа нужно сохранить в переменную и у нее вызывать _showWindow()
2) Методы название через нижнее подчеркивание, означают что приватные и используются только внутри класса. Сейчас ты приватный метод используешь вне класса

2021-04-23 08:56 UTC, igr-ik commented on sources/views/contactsDetails/contactsList.js
> +		});
Здесь как с таблицей, можно было в конфиге самого листа описать событие

2021-04-23 08:56 UTC, igr-ik commented on sources/views/contactsDetails/userInfo.js
> +                    <img class ="status__img" src=${image || empty} alt="User Photo">
Некорректное названия класса "status__img". Аватарка пользователя это не статус

2021-04-23 08:56 UTC, igr-ik commented on sources/views/toolbar.js
> +	}
Это лучше сделать через систему событий
Здесь в init слушаешь событие, например "change-toolbar-title"
this.on(this.app, "change-toolbar-title", (title) => {
this.toolbar.setValues({
			projects: title
		});
});

Потом на других страница в init вызываешь это событие с названием страницы
this.app.callEvent("change-toolbar-title", ["Название страницы"]);

2021-04-23 08:56 UTC, igr-ik commented on sources/views/window/popup.js
> +				this.getRoot().hide();
У тебя уже есть метод _hideWindow(), который очищает форму и валидацию и закрывает попап

2021-04-23 08:56 UTC, igr-ik commented on sources/models/activities.js
> +			item.DueDate = webix.i18n.parseFormatDate(item.DueDate);
Это лишнее. из строки в дату ты уже сделал в $init

2021-04-23 09:04 UTC, ilya-xbsoftware commented on sources/constants/urls.js
> +const LOCAL_PHOTO_URL = "./sources/images/man.png";
заменил на PLACEHOLDER_AVATAR_URL

2021-04-23 13:41 UTC, ilya-xbsoftware commented on sources/views/activities.js
> +								this.ui(new PopupView(this.app, ""))._showWindow();
исправил

2021-04-23 13:42 UTC, ilya-xbsoftware commented on sources/views/activities.js
> +		});
понял, исправил

2021-04-23 15:14 UTC, igr-ik approved these changes, later dismissed

2021-04-23 17:46 UTC, HelgaListopad commented on sources/views/activities.js
> +								this.ui(new PopupView(this.app, ""))._showWindow();
Эм, нет, не исправил. 
Всё ещё по клику на кнопку создаётся новый экземпляр, разве что с публичным методом show. 
Потом ты его закрываешь (разрушаешь) через `close`, что предотвращает все конфликты, но пересоздавать одно и то же окно по каждому клику на кнопку в этом задании - жёсткое излишество.

Как и сказал @igr-ik 

> Экземпляр попапа нужно сохранить в переменную и у нее вызывать showWindow()

Базовый пример дан в лекциях и в [этом разделе](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/popups-and-windows#windows-as-jet-view-classes) доки. В твоём случае:
- на `init` твоей вьюшки activities создаёшь один попап
```
this.popup = this.ui( ... );
```
- когда нужно, вызываешь от него `showWindow`, передавая туда нужные параметры для того, чтобы определить, edit это или add (`id` достаточно);
- в зависимости от этого параметра в попапе меняется текст в двух местах и на коллекции вызывается add/updateItem соответственно;
- в `_hideWindow` чистится форма, чистится валидация, окно прячется через `hide`

По сути, та логика, которую ты сейчас уже применяешь в попапе, переносится с его создания/разрушения на его открытие/сокрытие (+ надо очистить форму от старых значений).

2021-04-23 18:22 UTC, HelgaListopad requested changes

2021-04-23 18:22 UTC, HelgaListopad commented on sources/views/activities.js
> +		activities.waitData.then(() => {
Именно `sync` можно вызывать без `waitData` - коллекция дождётся данных и передаст их в таблицу по готовности.
А вот если надо было бы обратиться к данным коллекции (как это делается ниже,`getFirstId`) - тогда без 
 `waitData` никак.

2021-04-23 18:22 UTC, HelgaListopad commented on sources/views/activities.js
> +								this.ui(new PopupView(this.app, "")).showWindow();
См. развёрнутый комментарий про инициализацию окон.

2021-04-23 18:22 UTC, HelgaListopad commented on sources/views/contactsDetails/userInfo.js
> +             <section class="user-template">
Табуляцию тут я бы предложила выровнять - съехавший левее код видеть немного тяжело

2021-04-23 18:22 UTC, HelgaListopad commented on sources/views/activities.js
> +							header: ["Due date", {content: "datepickerFilter"}],
Этому фильтру нужно дать "менее строгий" метод фильтрации через `compare`.
Почему: он фильтрует даты учётом времени.
Если ты выберешь в фильтре дату, она будет со временем 00:00:00
У активностей время в DueDate может отличаться - как следствие, на нужную дату можно не увидеть совпадений

Как можно поменять `compare` для дат и ничего не сломать:
- [проверить](https://docs.webix.com/api___isdate.html), пришла ли из данных дата,
- если да, [копировать](https://docs.webix.com/api__date_copy.html) это значение 
- выставить ему время по нулям: `.setHours(0, 0, 0);`
- сравнить значение фильтра уже с этим результатом : `a*1 == b*1`

2021-04-23 18:22 UTC, HelgaListopad commented on sources/views/activities.js
> +							this.ui(new PopupView(this.app, "", editingItem)).showWindow();
См. всё тот же комментарий про переиспользование окон

2021-04-24 11:30 UTC, ilya-xbsoftware commented on sources/views/activities.js
> +								this.ui(new PopupView(this.app, ""))._showWindow();
разобрался, все поправил. 
Теперь только скрываю/открываю popup. 
Но при клике на edit, я передаю объект.

2021-04-24 11:52 UTC, ilya-xbsoftware commented on sources/views/contactsDetails/userInfo.js
> +             <section class="user-template">
Ольга, это странно у меня все красиво выравнено было. 
Сейчас немного поменял расположение. 
У меня вот так: 
 
![image](https://user-images.githubusercontent.com/82055260/115957708-afa5c780-a50c-11eb-8b78-325de8350126.png)

2021-04-24 13:55 UTC, HelgaListopad commented on sources/views/activities.js
> +								this.ui(new PopupView(this.app, ""))._showWindow();
@ilya-xbsoftware а был ли коммит с этими изменениями?

2021-04-24 19:57 UTC, ilya-xbsoftware commented on sources/views/activities.js
> +								this.ui(new PopupView(this.app, ""))._showWindow();
я решил, что исправлю все, а потом уже внесу все изменения. 
Наверное не стоило было комментарий оставлять.

2021-04-24 22:28 UTC, HelgaListopad commented on sources/views/activities.js
> +								this.ui(new PopupView(this.app, ""))._showWindow();
Поняла. 
Да, лучше всего давать комментарии после соответствующих коммитов, чтобы ревьюверы не искали код :)

2021-04-24 22:30 UTC, HelgaListopad approved these changes

2021-04-24 22:34 UTC, HelgaListopad commented
@ilya-xbsoftware так как изменения ты делал по моему ревью, мне кажется, Игоря можно второй раз не просить смотреть код (или придётся подождать до понедельника). 
Если отзовёшь этот реквест - вмержу код в мастер сама, как и предупреждала в скайпе (прошу это сделать, чтобы не было недопонимания и внезапного для тебя мержа ветки)

2021-04-25 10:35 UTC, HelgaListopad approved these changes

2021-04-25 10:35 UTC, merged