Stage2 Completed
ilya-xbsoftware/jet-start pull request #2
Opened 2021-04-28 10:51 UTC by ilya-xbsoftware

2021-04-28 13:38 UTC, igr-ik commented on sources/constants/events.js
> +	SHOW_POPUP: "open-popup",
Логично было бы и ивент так же назвать "show-popup"

2021-04-28 13:38 UTC, igr-ik commented on sources/constants/events.js
> +	SELECT_LIST: "showContactInfo"
1) Названия константы и имя события совсем разные.
2) Придерживайся единого стиля кода, если начал именовать события разделяя слова через "-", то так и продолжай везде. Чтобы не было, что где-то слова разделены через "-", а где-то через camel case

2021-04-28 13:38 UTC, igr-ik commented on sources/views/activities-elements/activitiesDataTable.js
> +								return filter * 1 === date * 1;
Для чего умножения на один?
Без этой логики, "datepickerFilter" не работал правильно?

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +			css: "contactBigForm",
Имена css классов, принято разделять через "-". Это касается всех css классов в приложении, не только в этом месте

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +									invalidMessage: {text: "Can not be empty", type: "error"}
"Can not be empty" - часто повторяемый текст, можно было бы вынести в константу.
В invalidMessage не обязательно передавать объект, можно сделать проще
invalidMessage: "Can not be empty"

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +		this._urlId = this.getParam("id", true);
this._urlId - id урла или все же пользователя?

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +		this._twoActionsBtn = this.$$("twoActionsBtn");
this._twoActionsBtn - очень странное названия свойства

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +			const id = this._urlId;
Эти переменные можно было не создавать. Можно на прямую работать со свойствами объекта.

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +		}
const userId = id || contacts.getFirstId();
this.app.callEvent(events.SELECT_LIST, [userId]);

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +	_setTitleValue(action) {
Названия метода, говорит о том, что он устанавливает названия в заголовок, но при этом происходят следующие вещи:
1) Изменяется имя заголовка;
2) Изменяется значения у кнопки;
3) В какой-то ситуации очищается форма;

Разработчик который будет работать с твоим кодом, по названию метода. не ожидает что к пункту 1, будет срабатывать пункт 2 и в какой-то момент 3.

Если метод называется _setTitleValue, то есть "установить значения в заголовок", то метод должен уметь делать только это, и ничего другого

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +		}
Проверь в приложении, когда сохраняешь форму с незаполненными полями, то появляется эта ошибка, и при этом данные сохраняются

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contact-form.js
> +		if (PLACEHOLDER_AVATAR_URL) {
Почему PLACEHOLDER_AVATAR_URL может не быть? Это же константа, она всегда есть.

2021-04-28 13:38 UTC, igr-ik commented on sources/views/contacts-elements/contactsFileController.js
> +export default class ContactsFileController extends JetView {
ContactsFileController
Это таблица а не контроллер

2021-04-28 15:12 UTC, ilya-xbsoftware commented on sources/views/contact-form.js
> +									invalidMessage: {text: "Can not be empty", type: "error"}
в stage 3 надо будет делать локализацию ...

2021-04-28 15:42 UTC, ilya-xbsoftware commented on sources/views/contact-form.js
> +		}
дописал return

2021-04-28 15:43 UTC, ilya-xbsoftware commented on sources/views/contact-form.js
> +			css: "contactBigForm",
Исправил, стараюсь такого не допускать.

2021-04-28 16:15 UTC, igr-ik approved these changes

2021-04-30 08:05 UTC, HelgaListopad requested changes
Есть ещё два бага. Тестируй, пожалуйста, свой код. 
Если вдруг на момент запроса ревью какая-то проблема известна, но решения нет - оставляй вопросы в pull request description.

1. Если открыта форма **Add** contact, в листе и параметрах урла сохраняется выбранный ранее контакт. Получается нестыковка:
- сам лист активен и ты можешь уйти с формы Add, выбрав какой-то контакт,
- но невозможно перейти на контакт, на котором уже стоит selection

Поведение надо унифицировать - либо снимать selection/url param, либо отключать лист и позволять уйти из формы добавления только по кнопке Cancel


2. Переход по контактам и фильтрация их activities

- выбери контакт
- отфильтруй его activities
- выбери другой контакт - фильтры не сбросятся/не будут применены для новых данных

2021-04-30 08:05 UTC, HelgaListopad commented on sources/views/contact-form.js
> +									invalidMessage: {text: "Can not be empty", type: "error"}
Возможно, ты перепутал возможности метода `webix.message()` (всплывающие сообщения) и это свойство.
invalidMessage не может быть объектом ([сверься с API](https://docs.webix.com/api__ui.text_invalidmessage_config.html)) - сейчас у тебя не отображается ни одно сообщение как раз из-за этой ошибки. Было бы неплохо протестировать свой код.)

2021-04-30 08:05 UTC, HelgaListopad commented on sources/views/contacts-userInfo.js
> +				contacts.remove(id);
Никак не обрабатывается удаление в UI.
После удаления
- остаётся то же ID в URL
- открыто Info удалённого контакта

2021-04-30 13:04 UTC, ilya-xbsoftware commented on sources/views/contacts-userInfo.js
> +				contacts.remove(id);
исправил

2021-04-30 15:35 UTC, HelgaListopad approved these changes

2021-05-01 08:45 UTC, merged