Stage3
ilya-xbsoftware/jet-start pull request #3
Opened 2021-05-05 09:57 UTC by ilya-xbsoftware

2021-05-05 10:56 UTC, igr-ik reviewed
1) Заметил что часто используется этот конфирм
webix.confirm({
									title: _("areYouSure"),
									ok: _("ok"),
									cancel: _("cancel")
								})

Можно было бы вынести его отдельный файл, и использовать везде где нужно.

2) Пересмотри пожалуйста, локали, чтобы названия свойства в объекте, хоть приблизительно совпадала с переводом. Чтобы не было такого - update: "Сохранено !"

2021-05-05 10:56 UTC, igr-ik commented on sources/locales/ru.js
> +	Language: "Язык",
Придерживайся единого стиля, если начал именовать свойства с маленькой буквы, то именуй так все.

2021-05-05 10:56 UTC, igr-ik commented on sources/locales/ru.js
> +	addNew: "Добавить",
Уже есть add: "Добавить"
Может ты имел ввиду "Добавить новый"?

2021-05-05 10:56 UTC, igr-ik commented on sources/locales/ru.js
> +	deletePhoto: "удалить",
Тоже как-то не логично, дубликаты получаются
changePhoto: "изменить" - может "изменить фото"?
deletePhoto: "удалить" - может "удалить фото"?

2021-05-05 10:56 UTC, igr-ik commented on sources/locales/ru.js
> +	edited: "Контакт был изменен",
added - addedNewContact
edited - editedContact

2021-05-05 10:56 UTC, igr-ik commented on sources/locales/ru.js
> +	areYouSure: "Вы уверены ?",
Зачем пробелы добавляешь перед знаками препинания?
Во всех переводах такое

2021-05-05 10:56 UTC, igr-ik commented on sources/locales/ru.js
> +	update: "Сохранено !",
Логичнее было бы "Обновлено"

2021-05-05 10:56 UTC, igr-ik commented on sources/locales/ru.js
> +	ok: "ОК",
Возможно, правильно было бы не "ОК" а "Да".
Особенно это актуально в конфирме, когда нужно подтвердить удаления. В русском варианте получается "Отмена" и "ОК". Как-то совсем не по-русски, логичнее - "Отмена" и "Да".

2021-05-05 13:09 UTC, igr-ik approved these changes

2021-05-05 17:13 UTC, HelgaListopad requested changes
Насколько я вижу, сейчас иконка отрисовывается только в темплейте контакта (для его статуса).
Для таблицы activities ещё можно сомневаться, добавлять или нет, но если иконок нет в их собственном списке - это уже не очень хорошо. Одни названия мало о чём говорят.
![image](https://user-images.githubusercontent.com/7587383/117181225-ac002380-addd-11eb-93cb-40ccdc485536.png)
Попробуй добавить иконки
- в settings, в ячейку и эдитор 
- в activities table, чтобы всегда отрисовывалась иконка, соответствующая активности

2021-05-05 17:13 UTC, HelgaListopad commented on sources/views/settings/settingsTable.js
> +							width: 100,
Ширина кнопки маловата для русской локали
Или выставь фиксированный размер побольше, или попробуй использовать `autowidth`

2021-05-06 10:36 UTC, HelgaListopad requested changes

2021-05-06 10:36 UTC, HelgaListopad commented on sources/views/activities-elements/activitiesDataTable.js
> +		const getActivityTypeData = activityTypes.getItem(item);
Здесь вскрылась другая проблема. Так как activity types и statuses теперь можно удалять, не хватает проверки на то, а возвращает ли вообще что-нибудь `getItem`

2021-05-06 10:36 UTC, HelgaListopad commented on sources/views/activities-elements/activitiesDataTable.js
> +		const getActivityTypeData = activityTypes.getItem(item);
То же самое будет актуально для contacn info:
```
const status = statuses.getItem(this._contact.StatusID);
```

2021-05-06 11:36 UTC, ilya-xbsoftware commented on sources/views/activities-elements/activitiesDataTable.js
> +		const getActivityTypeData = activityTypes.getItem(item);
исправил

2021-05-06 11:42 UTC, HelgaListopad requested changes

2021-05-06 11:42 UTC, HelgaListopad commented on sources/views/contacts-userInfo.js
> +			const status = statuses.getItem(this._contact.StatusID) || false;
Пытаться брать какое-то свойство от false не очень хорошо
Если хочешь использовать заглушку, можно преобразовать в
```js
const status = statuses.getItem(id);
const statusText = status && status.Value ? status.Value : "N/A"
```

2021-05-06 11:42 UTC, HelgaListopad commented on sources/views/contacts-userInfo.js
> +			const status = statuses.getItem(this._contact.StatusID) || false;
То же самое для ActivitiesDataTable

2021-05-06 12:14 UTC, ilya-xbsoftware commented on sources/views/contacts-userInfo.js
> +			const status = statuses.getItem(this._contact.StatusID) || false;
окей, понял. 
Исправил.

2021-05-06 12:28 UTC, HelgaListopad approved these changes

2021-05-06 12:31 UTC, merged